easy_admin:
   site_name: '<em style="font-size: 80%; font-weight: bold">Administration</em>'
   entities:
         Product:
           class: App\Entity\Product
           role: ROLE_ADMIN
           form:
              fields:
                 - { property: 'name'}
                 - { property: 'price'}
                 - { property: 'description'}
                 - { property: 'promo'}
                 - { property: 'updatedAt'}
                 - { property: 'category'}
                 - { property: 'imageFile', type: 'file' }
         Category:
            class: App\Entity\Category
            form:
              fields:
                 - { property: 'name'}



